<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_public.proto

namespace Game_public;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class CreateRoomRequest extends \Google\Protobuf\Internal\Message
{
    private $room_id = 0;
    private $owner = '';
    private $kwargs = '';

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getOwner()
    {
        return $this->owner;
    }

    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;
    }

    public function getKwargs()
    {
        return $this->kwargs;
    }

    public function setKwargs($var)
    {
        GPBUtil::checkString($var, True);
        $this->kwargs = $var;
    }

}

class CreateRoomResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

}

class EnterRoomRequest extends \Google\Protobuf\Internal\Message
{
    private $room_id = 0;
    private $player = '';
    private $info = '';

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    public function getInfo()
    {
        return $this->info;
    }

    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;
    }

}

class EnterRoomResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $room_id = 0;
    private $owner = '';
    private $kwargs = '';
    private $rest_cards = 0;
    private $player;

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getOwner()
    {
        return $this->owner;
    }

    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;
    }

    public function getKwargs()
    {
        return $this->kwargs;
    }

    public function setKwargs($var)
    {
        GPBUtil::checkString($var, True);
        $this->kwargs = $var;
    }

    public function getRestCards()
    {
        return $this->rest_cards;
    }

    public function setRestCards($var)
    {
        GPBUtil::checkUint32($var);
        $this->rest_cards = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Game_public\EnterRoomResponse_Player::class);
        $this->player = $var;
    }

}

class EnterRoomResponse_Player extends \Google\Protobuf\Internal\Message
{
    private $seat = 0;
    private $player = '';
    private $info = '';
    private $status = 0;
    private $is_online = 0;
    private $total_score = 0;

    public function getSeat()
    {
        return $this->seat;
    }

    public function setSeat($var)
    {
        GPBUtil::checkUint32($var);
        $this->seat = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    public function getInfo()
    {
        return $this->info;
    }

    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;
    }

    public function getIsOnline()
    {
        return $this->is_online;
    }

    public function setIsOnline($var)
    {
        GPBUtil::checkUint32($var);
        $this->is_online = $var;
    }

    public function getTotalScore()
    {
        return $this->total_score;
    }

    public function setTotalScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_score = $var;
    }

}

class EnterRoomOtherResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $player = '';
    private $seat = 0;
    private $info = '';

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    public function getSeat()
    {
        return $this->seat;
    }

    public function setSeat($var)
    {
        GPBUtil::checkUint32($var);
        $this->seat = $var;
    }

    public function getInfo()
    {
        return $this->info;
    }

    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;
    }

}

class EnterRoomWebResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $room_id = 0;
    private $player = '';
    private $game_type = 0;
    private $app_id = 0;

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    public function getGameType()
    {
        return $this->game_type;
    }

    public function setGameType($var)
    {
        GPBUtil::checkUint32($var);
        $this->game_type = $var;
    }

    public function getAppId()
    {
        return $this->app_id;
    }

    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;
    }

}

class ExitRoomRequest extends \Google\Protobuf\Internal\Message
{

}

class ExitRoomResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $player = '';

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

}

class ExitRoomWebResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $room_id = 0;
    private $player = '';
    private $game_type = 0;
    private $app_id = 0;

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    public function getGameType()
    {
        return $this->game_type;
    }

    public function setGameType($var)
    {
        GPBUtil::checkUint32($var);
        $this->game_type = $var;
    }

    public function getAppId()
    {
        return $this->app_id;
    }

    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;
    }

}

class DismissRoomRequest extends \Google\Protobuf\Internal\Message
{

}

class DismissRoomResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $flag = 0;

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getFlag()
    {
        return $this->flag;
    }

    public function setFlag($var)
    {
        GPBUtil::checkUint32($var);
        $this->flag = $var;
    }

}

class DismissRoomWebResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $room_id = 0;
    private $game_type = 0;
    private $app_id = 0;
    private $owner = '';

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getGameType()
    {
        return $this->game_type;
    }

    public function setGameType($var)
    {
        GPBUtil::checkUint32($var);
        $this->game_type = $var;
    }

    public function getAppId()
    {
        return $this->app_id;
    }

    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;
    }

    public function getOwner()
    {
        return $this->owner;
    }

    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;
    }

}

class RefundWebResponse extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $room_id = 0;
    private $game_type = 0;
    private $app_id = 0;
    private $owner = '';

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getGameType()
    {
        return $this->game_type;
    }

    public function setGameType($var)
    {
        GPBUtil::checkUint32($var);
        $this->game_type = $var;
    }

    public function getAppId()
    {
        return $this->app_id;
    }

    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;
    }

    public function getOwner()
    {
        return $this->owner;
    }

    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;
    }

}

class SponsorVoteResponse extends \Google\Protobuf\Internal\Message
{
    private $room_id = 0;
    private $sponsor = '';
    private $expire_seconds = 0;

    public function getRoomId()
    {
        return $this->room_id;
    }

    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    public function getSponsor()
    {
        return $this->sponsor;
    }

    public function setSponsor($var)
    {
        GPBUtil::checkString($var, True);
        $this->sponsor = $var;
    }

    public function getExpireSeconds()
    {
        return $this->expire_seconds;
    }

    public function setExpireSeconds($var)
    {
        GPBUtil::checkUint32($var);
        $this->expire_seconds = $var;
    }

}

class PlayerVoteRequest extends \Google\Protobuf\Internal\Message
{
    private $flag = false;

    public function getFlag()
    {
        return $this->flag;
    }

    public function setFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->flag = $var;
    }

}

class PlayerVoteResponse extends \Google\Protobuf\Internal\Message
{
    private $flag = false;
    private $player = '';

    public function getFlag()
    {
        return $this->flag;
    }

    public function setFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->flag = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a8f0a0a1167616d655f7075626c69632e70726f746f120b67616d655f70" .
    "75626c696322430a11437265617465526f6f6d52657175657374120f0a07" .
    "726f6f6d5f696418012001280d120d0a056f776e6572180220012809120e" .
    "0a066b776172677318032001280922220a12437265617465526f6f6d5265" .
    "73706f6e7365120c0a04636f646518012001280d22410a10456e74657252" .
    "6f6f6d52657175657374120f0a07726f6f6d5f696418012001280d120e0a" .
    "06706c61796572180220012809120c0a04696e666f180320012809228a02" .
    "0a11456e746572526f6f6d526573706f6e7365120c0a04636f6465180120" .
    "01280d120f0a07726f6f6d5f696418022001280d120d0a056f776e657218" .
    "0320012809120e0a066b776172677318042001280912120a0a726573745f" .
    "636172647318052001280d12350a06706c6179657218062003280b32252e" .
    "67616d655f7075626c69632e456e746572526f6f6d526573706f6e73652e" .
    "506c617965721a6c0a06506c61796572120c0a047365617418012001280d" .
    "120e0a06706c61796572180220012809120c0a04696e666f180320012809" .
    "120e0a0673746174757318042001280d12110a0969735f6f6e6c696e6518" .
    "052001280d12130a0b746f74616c5f73636f726518062001280d22520a16" .
    "456e746572526f6f6d4f74686572526573706f6e7365120c0a04636f6465" .
    "18012001280d120e0a06706c61796572180220012809120c0a0473656174" .
    "18032001280d120c0a04696e666f18042001280922680a14456e74657252" .
    "6f6f6d576562526573706f6e7365120c0a04636f646518012001280d120f" .
    "0a07726f6f6d5f696418022001280d120e0a06706c617965721803200128" .
    "0912110a0967616d655f7479706518042001280d120e0a066170705f6964" .
    "18052001280d22110a0f45786974526f6f6d5265717565737422300a1045" .
    "786974526f6f6d526573706f6e7365120c0a04636f646518012001280d12" .
    "0e0a06706c6179657218022001280922670a1345786974526f6f6d576562" .
    "526573706f6e7365120c0a04636f646518012001280d120f0a07726f6f6d" .
    "5f696418022001280d120e0a06706c6179657218032001280912110a0967" .
    "616d655f7479706518042001280d120e0a066170705f696418052001280d" .
    "22140a124469736d697373526f6f6d5265717565737422310a134469736d" .
    "697373526f6f6d526573706f6e7365120c0a04636f646518012001280d12" .
    "0c0a04666c616718022001280d22690a164469736d697373526f6f6d5765" .
    "62526573706f6e7365120c0a04636f646518012001280d120f0a07726f6f" .
    "6d5f696418022001280d12110a0967616d655f7479706518032001280d12" .
    "0e0a066170705f696418042001280d120d0a056f776e6572180520012809" .
    "22640a11526566756e64576562526573706f6e7365120c0a04636f646518" .
    "012001280d120f0a07726f6f6d5f696418022001280d12110a0967616d65" .
    "5f7479706518032001280d120e0a066170705f696418042001280d120d0a" .
    "056f776e6572180520012809224f0a1353706f6e736f72566f7465526573" .
    "706f6e7365120f0a07726f6f6d5f696418012001280d120f0a0773706f6e" .
    "736f7218032001280912160a0e6578706972655f7365636f6e6473180420" .
    "01280d22210a11506c61796572566f746552657175657374120c0a04666c" .
    "616718012001280822320a12506c61796572566f7465526573706f6e7365" .
    "120c0a04666c6167180120012808120e0a06706c61796572180220012809" .
    "620670726f746f33"
));

